;
; LAB1_1.asm
;
; Created: 20/03/2023 9:16:48 SA
; Author : Thanh Binh _ 2010925
;


; Replace with your application code
.EQU	OUTPUT_DDR	=	DDRA
.EQU	OUTPUT_PORT	=	PORTA
.EQU	OUTPUT_PIN	=	PINA

.EQU	INPUT_DDR	=	DDRB
.EQU	INPUT_PORT	=	PORTB
.EQU	INPUT_PIN	=	PINB


LDI		R16,			0X00
OUT		INPUT_DDR,		R16
LDI		R16,			0XFF
OUT		INPUT_PORT,		R16

LDI		R16,			0XFF
OUT		OUTPUT_DDR,		R16

LOOP:

IN		R16,			INPUT_PIN	
COM		R16
OUT		OUTPUT_PORT,	R16		

RJMP	LOOP			
